"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['print_sheet_GUI.py']
OPTIONS = {'iconfile': '/Users/willic130/Documents/GitHub/PVI_Scripts/green_virus_icon.icns'}

setup(
    app=APP,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
